### ISSUE TITLE
Error During Decompression in install.sh Execution

### ISSUE THREAD

**Issue by KiAkize** [eawilson-CompBio/HLA-Inception#1]
During installation, the following output was generated:
```
extracting data files

gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now

gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now
```

Upon investigation, it appears that the error occurs while extracting files with the following commands:

```bash
echo "extracting data files"
tar -xzf data/Dist.json.tgz -C data/
tar -xzf data/LO.json.tgz -C data/
```

How can this installation issue be resolved?

**Comment by eawilson-CompBio** [comment]
What is the is the size of the downloaded compressed files? My guess is that they did not download properly. Also, do you have git LFS installed?

**Comment by KiAkize** [comment]
Thank you for your response. After updating Git LFS, the installation works properly :)
