### ISSUE TITLE
Installation issue due tar extraction 

### ISSUE THREAD

**Issue by felipebatalini** [eawilson-CompBio/HLA-Inception#2]
Dear Eric,

Thanks for the easy-to-follow installation instructions here on GitHub.
I wanted to let you know that I got error using the install.sh with bash because at the tar extraction step it did not recognize the .tgz files as git-lfs even though I had git-lfs installed properly. I was able to complete installation by pulling the lfs manually from the HLA-inception/data directory using:
```
git lfs pull
```
And then re-run:
```
bash install.sh 
```
HLA-inception is working well but wanted to let you about this little bug for future versions.

Thank you very much,
Felipe

**Comment by eawilson-CompBio** [comment]
Hey Felipe,

Thanks for spotting this issue! I have updated the readme to guide users to use git lfs to clone the repository directly.

Best,
Eric
